language: csharp
solution: ./src/Projbook.sln
install:
  - nuget restore ./src/Projbook.sln
  - nuget install NUnit.Runners -Version 3.4.1 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release ./src/Projbook.sln
  - xbuild /p:Configuration=ReleaseNoPdf ./src/Projbook.sln
  - mono testrunner/NUnit.ConsoleRunner.3.4.1/tools/nunit3-console.exe ./src/Projbook.Tests/bin/ReleaseNoPdf/Projbook.Tests.dll
