language: csharp
solution: ./src/Projbook.sln
install:
  - nuget restore ./src/Projbook.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - cd src
  - xbuild /p:Configuration=Release ./Projbook.sln
  - mono testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Projbook.Tests/bin/Release/Projbook.Tests.dll
  - cd ../
  - bash ./build/deploy-doc.sh
  - bash ./build/post-build.sh
deploy:
  provider: script
  script: ./build/deploy-nuget.sh
  skip_cleanup: true
  on:
    tags: true